### ISSUE TITLE
Crash on unplugging audio sink

### ISSUE THREAD

**Issue by mbrea-c** [mbrea-c/pystatus#1]
Crash on unplugging audio sink with the following output
```
2022-02-05T21:10:02.33062 Traceback (most recent call last):
2022-02-05T21:10:02.33063   File "/home/manuel/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pystatus/modules/volume_module.py", line 45, in _init_async
2022-02-05T21:10:02.33064     await self._update()
2022-02-05T21:10:02.33064   File "/home/manuel/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pystatus/modules/volume_module.py", line 52, in _update
2022-02-05T21:10:02.33065     self._update_sinks(name_volume_dict)
2022-02-05T21:10:02.33065   File "/home/manuel/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pystatus/modules/volume_module.py", line 36, in _update_sinks
2022-02-05T21:10:02.33066     for name, label in self.sinks.items():
2022-02-05T21:10:02.33066 RuntimeError: dictionary changed size during iteration
```

**Comment by mbrea-c** [comment]
Fixed by [93d093d](https://github.com/mbrea-c/pystatus/commit/93d093db7ce0b73161fa18d7cacb76275ccb73c6)
