### ISSUE TITLE
Issue on config.

### ISSUE THREAD

**Issue by lidgnulinux** [mbrea-c/pystatus#2]
I try to run pystatus and I get this. 

```
[ahmad pystatus]$ poetry run pystatus pystatus
/home/ahmad/compile/senin-29-08/pystatus/src/pystatus/main.py:24: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0
.7') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GtkLayerShell, Gdk, Notify
[ERROR(root):config.py:__init__] Could not find any valid config file. Exiting...
```

Whats the correct way to launch it ? Thanks

**Comment by lidgnulinux** [comment]
Configuration problem is solved and then I face this : 

```
[ahmad pystatus]$ pystatus pystatus -o LVDS-1
[INFO(root):config.py:read_config_from_path] Loaded config file /home/ahmad/.config/pystatus/pystatus.toml
Traceback (most recent call last):
  File "/home/ahmad/.local/lib/python3.10/site-packages/pystatus/main.py", line 65, in <lambda>
    lambda app: build_ui(application=app, bar_name=bar_name, output=output),
  File "/home/ahmad/.local/lib/python3.10/site-packages/pystatus/main.py", line 75, in build_ui
    config = Config()
  File "/home/ahmad/.local/lib/python3.10/site-packages/pystatus/config.py", line 25, in __init__
    for name, bar_dict in toml_dict["bars"].items():
KeyError: 'bars'
```

**Comment by mbrea-c** [comment]
Hey, thanks for the interest! Can you send the contents of your pystatus.toml?

**Comment by mbrea-c** [comment]
Just added an example `pystatus.toml` to the repository.Try these steps to get it to work:
 1, Copy the example config to `$HOME/.config/pystatus/pystatus.toml`.
 2. Launch by running `pystatus status`.

If this still doesn't work, make sure you pull the latest master version from this repository and try again. Let me know if it's still broken after that and I can take a look later.

**Comment by lidgnulinux** [comment]
It works now, thanks @mbrea-c . Have a good day. I'll close it now.
